# Turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=y

# Increase transmit power level
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# пробую отключить множественные случайные прожатия
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10
